refactor(citations): refactoring
aeris-data/aeris-metadata-components-vjs pull request #15
Opened 2019-01-21 15:26 UTC by ttdev2toulouse

2019-01-22 08:35 UTC, samirboumaza approved these changes

2019-01-23 12:55 UTC, vlhung commented
il y a des conflits dans la branche :-D

2019-01-23 13:01 UTC, vlhung commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-citations/components/aeris-metadata-citations.vue
> +    }
Je pense que l'on devrait laisser au composant parent de gérer directement la langue de ses composants fils

2019-01-23 13:01 UTC, vlhung commented on src/demo/modules/aeris-metadata-blocks/submodules/aeris-metadata-citations/aeris-metadata-citations-test.vue
> +  name: "aeris-metadata-citations-test",
un espace entre les props du composant vue :-)

2019-01-24 07:57 UTC, samirboumaza commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-citations/components/aeris-metadata-citations.vue
> +    }
oui c'est plus naturel, c'est mieux de partir sur cette règle du parent qui gère le langue & co

2019-02-04 11:23 UTC, vlhung requested changes
Les fichiers register et index sont vides. Il faudrait faire un fix eslint sur les fichiers que tu as modifié :-)

2019-02-04 11:23 UTC, vlhung commented on src/demo/main.js
> +});
tu peux enlever languageStore et store ici. On a déjà un composant qui gère la langue dans commons

2019-02-04 11:23 UTC, vlhung commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-citations/components/aeris-metadata-citations.vue
> +    getLanguage(value) {
remplace getLanguage par language :-)

2019-02-04 11:23 UTC, vlhung commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-citations/components/aeris-metadata-citations.vue
> +    getLanguage() {
tu peux enlever getLanguage, c'est le parent qui gère la langue

2019-02-04 11:23 UTC, vlhung commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-citations/components/aeris-metadata-citations.vue
> +    this.$i18n.locale = this.language || this.getLanguage;
tu peux enlever  || this.getLanguage;

2019-02-05 16:35 UTC, merged