Aeris metadata publications
aeris-data/aeris-metadata-components-vjs pull request #18
Opened 2019-01-23 14:26 UTC by ttdev2toulouse

2019-01-23 14:49 UTC, esteban-em requested changes

2019-01-23 14:49 UTC, esteban-em commented on src/demo/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/aeris-metadata-publications-test.vue
> +          journal: "Atmos. Chem. Phys. Discuss.",
Si tu regardes dans les données JSON sur le site en prod il y a bien `journalName` et `journalSection`. Par exemple sur la fiche Iagos d'id "4d3be8dd-c41a-4f35-8ba6-722cf12e2de3" : 

```json
journalName: "Atmos. Chem. Phys. Discuss.",
journalSection: "in review"
```

Il faut adapter dans le code pour que ces données soient traitées et affichées correctement.

Si c'est pas clair n'hésite pas.

2019-01-23 14:49 UTC, esteban-em commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
> +            <span>{{ value.journal }}</span>
Du coup ici il faudrait garder le `journalName`

2019-01-23 14:49 UTC, esteban-em commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
>    created: function() {
Il faut aussi mettre les fonctions à la "sauce" ES6. C'est à dire qu'on ne met plus le mot clé `function` et du coup `created: function() {...}` devient `created() {...}`

2019-01-23 14:49 UTC, esteban-em commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
> +      console.log("String",JSON.parse(this.publication))
`console.log` à enlever

2019-01-23 14:49 UTC, esteban-em commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
>    watch: {
Vérifie aussi l'ordre des blocks en te servant de ça : 
https://gist.github.com/esteban-em/76b2bff239625d758a3e08e608db8bce

Par exemple, je pense que `data` devrait être plus haut dans le fichier. Mais vérifie quand même que la variable `deployed` est utilisée quelque part. Parce que si elle n'est pas utilisée, le `data` ne sert à rien.

2019-01-23 14:49 UTC, esteban-em commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publications.vue
> +  // destroyed: function() {
Ne laisse pas des blocs de code commentés. Supprime-les :wink:

2019-01-23 14:49 UTC, esteban-em commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publications.vue
> +    this.publications.forEach(publication => {
Enlève tout le `forEach` ici. On affichait juste les valeurs pour debugguer.

2019-01-23 14:49 UTC, esteban-em commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publications.vue
> +  // data() {
Commentaires à supprimer ici aussi.

2019-01-23 15:00 UTC, ttdev2toulouse commented
Très bien, merci.

Je vais revoir tout ça demain matin.

^^

Le mer. 23 janv. 2019 à 15:49, esteban-em <notifications@github.com> a
écrit :

> *@esteban-em* requested changes on this pull request.
> ------------------------------
>
> In
> src/demo/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/aeris-metadata-publications-test.vue
> <https://github.com/aeris-data/aeris-metadata-components-vjs/pull/18#discussion_r250221459>
> :
>
> > +
>
> +<script>
>
> +import AerisMetadataPublications from "../../../../../lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publications.vue";
>
> +export default {
>
> +  name: "aeris-metadata-publications-test",
>
> +  components: { AerisMetadataPublications },
>
> +  data() {
>
> +    return {
>
> +      publications: [
>
> +        {
>
> +          title: "Source attribution using FLEXPART and carbon monoxide emission",
>
> +          description: "blablablabla",
>
> +          authors: [
>
> +            "Sauvage, B., Fontaine, A., Eckhardt, S., Auby, A., Boulanger, D., Petetin, H., Paugam, R., Athier, G., Cousin, J.-M., Darras, S., Nédélec, P., Stohl, A., Turquety, S., Cammas, J.-P., and Thouret, V"
>
> +          ],
>
> +          journal: "Atmos. Chem. Phys. Discuss.",
>
>
> Si tu regardes dans les données JSON sur le site en prod il y a bien
> journalName et journalSection. Par exemple sur la fiche Iagos d'id
> "4d3be8dd-c41a-4f35-8ba6-722cf12e2de3" :
>
> journalName: "Atmos. Chem. Phys. Discuss.",
>
> journalSection: "in review"
>
> Il faut adapter dans le code pour que ces données soient traitées et
> affichées correctement.
>
> Si c'est pas clair n'hésite pas.
> ------------------------------
>
> In
> src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
> <https://github.com/aeris-data/aeris-metadata-components-vjs/pull/18#discussion_r250221682>
> :
>
> > @@ -43,7 +43,7 @@
>
>          <div>
>
>            <h5>{{ $t('journal') }}:</h5>
>
>            <p>
>
> -            <span>{{ value.journalName }}</span>
>
> +            <span>{{ value.journal }}</span>
>
>
> Du coup ici il faudrait garder le journalName
> ------------------------------
>
> In
> src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
> <https://github.com/aeris-data/aeris-metadata-components-vjs/pull/18#discussion_r250222151>
> :
>
> >        this.$i18n.locale = value;
>
>      }
>
>    },
>
>
>
> -  mounted: function() {
>
> -    this.$i18n.locale = this.lang;
>
> +  mounted() {
>
> +    this.$i18n.locale = this.language || this.getLanguage;
>
>    },
>
>
>
>    created: function() {
>
>
> Il faut aussi mettre les fonctions à la "sauce" ES6. C'est à dire qu'on ne
> met plus le mot clé function et du coup created: function() {...} devient created()
> {...}
> ------------------------------
>
> In
> src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
> <https://github.com/aeris-data/aeris-metadata-components-vjs/pull/18#discussion_r250222397>
> :
>
> > @@ -116,6 +116,7 @@ export default {
>
>      },
>
>
>
>      value: function() {
>
> +      console.log("String",JSON.parse(this.publication))
>
>
> console.log à enlever
> ------------------------------
>
> In
> src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
> <https://github.com/aeris-data/aeris-metadata-components-vjs/pull/18#discussion_r250223706>
> :
>
> > @@ -76,13 +76,13 @@ export default {
>
>    },
>
>
>
>    watch: {
>
>
> Vérifie aussi l'ordre des blocks en te servant de ça :
> https://gist.github.com/esteban-em/76b2bff239625d758a3e08e608db8bce
>
> Par exemple, je pense que data devrait être plus haut dans le fichier.
> Mais vérifie quand même que la variable deployed est utilisée quelque
> part. Parce que si elle n'est pas utilisée, le data ne sert à rien.
> ------------------------------
>
> In
> src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publications.vue
> <https://github.com/aeris-data/aeris-metadata-components-vjs/pull/18#discussion_r250224070>
> :
>
> >        this.$i18n.locale = value;
>
>      }
>
>    },
>
>
>
> -  destroyed: function() {
>
> -    document.removeEventListener(
>
> -      "aerisMetadataRefreshed",
>
> -      this.aerisMetadataListener
>
> -    );
>
> -    this.aerisMetadataListener = null;
>
> -  },
>
> +  // destroyed: function() {
>
>
> Ne laisse pas des blocs de code commentés. Supprime-les 😉
> ------------------------------
>
> In
> src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publications.vue
> <https://github.com/aeris-data/aeris-metadata-components-vjs/pull/18#discussion_r250224459>
> :
>
> >
>
> -  created: function() {
>
> -    console.log("Aeris Metadata Publications - Creating");
>
> -    this.$i18n.locale = this.lang;
>
> -    this.aerisMetadataListener = this.handleRefresh.bind(this);
>
> -    document.addEventListener(
>
> -      "aerisMetadataRefreshed",
>
> -      this.aerisMetadataListener
>
> -    );
>
> +  created() {
>
> +    this.publications.forEach(publication => {
>
>
> Enlève tout le forEach ici. On affichait juste les valeurs pour debugguer.
> ------------------------------
>
> In
> src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publications.vue
> <https://github.com/aeris-data/aeris-metadata-components-vjs/pull/18#discussion_r250224659>
> :
>
> >      }
>
>    }
>
> +  // data() {
>
>
> Commentaires à supprimer ici aussi.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aeris-data/aeris-metadata-components-vjs/pull/18#pullrequestreview-195553876>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AqwyXQ9NVvqydC-H8CJgv-PSm8R4NtD_ks5vGHZogaJpZM4aO5Cq>
> .
>

2019-01-23 15:01 UTC, vlhung commented
Il y a également index.js et register.js du module publications qui sont vides

2019-01-23 15:03 UTC, vlhung commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publications.vue
> +      :publication="JSON.stringify(publication)"
ici on utilise directement des objets donc il n'y a plus besoin de faire des transformations String <=> Objects
Avant, ces composants utilisées comme des customs éléments ce qui fait qu'il fallait transformer les objects en String. Ce n'est plus le cas avec le refactoring, plus de customs éléments, on n'utilise que des types correspondantes sans les transformer en String et vice versa.

2019-01-23 15:03 UTC, vlhung commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
>      },
On utilise les vrais types des props, ici il faudrait changer le type de publication

2019-01-23 16:26 UTC, esteban-em commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
>        default: "en"
`default: ""`

2019-01-28 10:20 UTC, esteban-em requested changes
Attention à la gestion du thème aussi. Tout est bleu alors que ce ne devrait être que les titres. En plus, en tout cas chez moi, il y a deux couleurs, alors qu'en  production il n'y en a qu'une. Tu peux t'inspirer du composant `<datepicker>` de commons pour la gestion du thème. Et si tu as besoin d'aide on peut en parler de vive voix :smile:

2019-01-28 10:20 UTC, esteban-em commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
> +          <h5 class="aeris-publication-header">{{ value.title }}</h5>
Je pense que ça serait bien que tout le titre du dropdown soit cliquable (`aeris-publication-header`). Parce que là c'est juste la flèche, et quand le bloc est grand on ne la repère pas forcément. Et puis c'est une petite "cible", donc ce n'est pas très accessible.

2019-01-28 10:20 UTC, esteban-em commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publication.vue
>          </div>
Attention, on a supprimé le composant `<aeris-cartouche>`, donc il faudrait reproduire son comportement sans l'utiliser.

2019-02-04 10:12 UTC, vlhung commented
npm run dev se lance  chez vous?

2019-02-04 10:31 UTC, vlhung requested changes

2019-02-04 10:31 UTC, vlhung commented on package.json
> +    "vue-custom-element": "^3.2.6",
à enlever

2019-02-04 10:31 UTC, vlhung commented on src/demo/app.vue
> -      <li><router-link to="/international-field">/international-field</router-link></li>
Ces tests ne sont pas bons? :-D

2019-02-04 10:31 UTC, vlhung commented on src/demo/main.js
> +Vue.use(vueCustomElement);
on n'utilise plus les custom elements

2019-02-04 10:31 UTC, vlhung commented on src/demo/main.js
> +} from "aeris-mixins";
à fixer avec eslints

2019-02-04 10:31 UTC, vlhung commented on src/demo/main.js
> -import AerisMetadataInternationalFieldTest from "./modules/aeris-metadata-international-field/aeris-metadata-international-field-test";
Ces tests sont bons, il ne faudrait pas les enlevers

2019-02-04 10:31 UTC, vlhung commented on src/demo/main.js
> -    {
A remettre ces tests

2019-02-04 10:31 UTC, vlhung commented on src/demo/main.js
> +    AerisMetadataPublicationsTest
il faudrait enlever:  metadata,
    quicklookGallery,
    metadataSynthesis,
    AerisMetadataCitationsTest,
    AerisMetadataPublicationsTest

2019-02-04 10:31 UTC, vlhung commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publications.vue
> +    },
pas de store, on laisse le parent de gérer la langue de ses fils

2019-02-04 10:31 UTC, vlhung commented on src/lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-publications/components/aeris-metadata-publications.vue
> +    this.$i18n.locale = this.language || this.getLanguage;
tu peux enlever || this.getLanguage

2019-02-04 11:08 UTC, vlhung commented
Il y a également index.js qui est toujours vide :-)

2019-02-06 12:20 UTC, merged