Aeris metadata title
aeris-data/aeris-metadata-components-vjs pull request #27
Opened 2019-02-01 14:34 UTC by ttdev2toulouse

2019-02-01 16:30 UTC, vlhung requested changes
Le composant title n'est pas encore terminé, il faut enlever les custom events etc.
Ces commentaires ne concernent que le composant title

2019-02-01 16:30 UTC, vlhung commented on src/demo/main.js
> +
on n'a plus besoin de vue-custom-element

2019-02-01 16:30 UTC, vlhung commented on package.json
> +    "vue-custom-element": "^3.2.6",
a-t-on encore besoin de custom element?

2019-02-01 16:30 UTC, vlhung commented on src/demo/main.js
> +
vue-resource est remplacé par vue-axios

2019-02-01 16:30 UTC, vlhung commented on src/demo/main.js
> -import axios from "axios";
on a besoin de axios et vue-axios pour les requêtes :-)

2019-02-01 16:30 UTC, vlhung commented on src/demo/main.js
> -import AerisMetadataInternationalFieldTest from "./modules/aeris-metadata-international-field/aeris-metadata-international-field-test";
pourquoi enlever ces blocks?

2019-02-01 16:30 UTC, vlhung commented on src/demo/main.js
> -      component: AerisMetadataDatapolicyTest
pareil qu'ici, pourquoi enlever ces blocks? ils ne sont pas bons? :-D

2019-02-01 16:30 UTC, vlhung commented on src/demo/main.js
> +      component: AerisMetadataTitleTest
Il faudrait remettre ces blocks et mets les tiens en plus. Car tu es parti sur une base mergée avec les derniers pull requests. Tes modifications vont enlever tous ce que l'on a ajouté avant ou créer des conflits pour rien.

2019-02-01 16:30 UTC, vlhung commented on src/demo/main.js
> +
on n'a pas besoin d'ajouter un store langue ici, vu qu'il n'est pas utilisé dans cette branche

2019-02-01 16:30 UTC, vlhung commented on src/demo/main.js
> +    AerisMetadataTitleTest
On n'a pas besoin d'ajouter ces composants ici, on ne les utilise pas ailleurs

2019-02-01 16:30 UTC, vlhung commented on src/demo/modules/aeris-metadata-blocks/submodules/aeris-metadata-title/aeris-metadata-title-test.vue
> +import AerisMetadataTitle from "../../../../../lib/modules/aeris-metadata-blocks/submodules/aeris-metadata-title/components/aeris-metadata-title.vue";
Il faudrait utiliser ce composant importé :-)

2019-02-04 08:30 UTC, samirboumaza commented on package.json
> +    "vue-custom-element": "^3.2.6",
non

2019-02-06 12:42 UTC, samirboumaza approved these changes

2019-02-06 13:10 UTC, merged